- name: Install Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: Enable Redis 6
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: Install Redis Server
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update MongoDB listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable Redis
  ansible.builtin.systemd:
    state: restarted
    name: redis
    enabled: yes

