- name: Configuring NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old App Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download Frontend App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Copy SystemD file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Copy MongoDB YUM Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb Server
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb.roboshop.internal
    file: "/app/schema/catalogue.js"
    idempotent: yes


#source common.sh
#
#component=catalogue
#schema_load=true
#schema_type=mongo
#
#NODEJS


#
#  LOAD_SCHEMA
#}