- name: Install Maven
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: APP PreRequisites
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Download Python Dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load

#
#  APP_PREREQ
#
#  print_head "Download Dependencies"
#  cd /app
#  pip3.6 install -r requirements.txt  &>>${LOG}
#  status_check
#
#  print_head "Update Passwords in Service File"
#  sed -i -e "s/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/" ${script_location}/files/${component}.service  &>>${LOG}
#  status_check
#
#  SYSTEMD_SETUP
#
#  LOAD_SCHEMA